### ISSUE TITLE
Tracking Contributions: Training team

### ISSUE THREAD

**Issue by angelasjin** [WordPress/five-for-the-future#179]
Following some conversations with Courtney (Traning team rep), there are a few suggested contributions for tracking:

- [ ] Updating site functionality, by tracking issues, assignments, and commenters in the [Learn Github](https://github.com/WordPress/Learn) _(probably done automatically by #178)_
- [x] Tracking who publishes lesson plans, workshops, courses on Learn WordPress. 
- [x] Add activity when added as a presenter for Learn workshop. Will be fixed by https://github.com/WordPress/wordpress.org/pull/84
- [ ] Ideally, we'll be able to also track who reviews them in the future as well.

**Comment by courtneyr-dev** [comment]
Looks good @angelasjin.  We also use HelpScout. https://github.com/WordPress/five-for-the-future/issues/177 

Tracking contributions on Learn would indicate also the development of the site and content on Learn. We are planning to implement hosting/facilitating SLS as well into our GitHub. 

We'd still want to track activity in Learn as occasionally folks will do a blast across the site. They might test code snippets on many posts, or swap screenshots due to a release, etc.  Our content has corresponding GitHub issues, but we also have need of folks to do a chunk of auditing that touches many issues. Tracking Learn activity would help identify that.

**Comment by courtneyr-dev** [comment]
Tracking contributions in sites could also help measure contributions on [https://jobs.wordpress.net](https://jobs.wordpress.net) as well. Posts there are reviewed and published.  They are received by a job poster submitting a form, sit as a Custom Post Type, and await one of the volunteers to vet and publish.

**Comment by iandunn** [comment]
> issues, assignments, and commenters in the [Learn Github](https://github.com/WordPress/Learn)

👍🏻 . [My comments for the Docs team](https://github.com/WordPress/five-for-the-future/issues/178#issuecomment-1105334203) applies equally to this.

> publishes lesson plans, workshops, courses [...] track who reviews them.

👍🏻

**Comment by iandunn** [comment]
> Tracking who publishes lesson plans, workshops, courses on Learn WordPress.

That's done now

**Comment by iandunn** [comment]
> Ideally, we'll be able to also track who reviews them in the future as well.

I have several questions for that. Lesson plans and workshops have these custom statuses:

* Draft
* Needs Vetting
* Approved For Video
* Declined
* More Info Requested
* Needs Video Review
* Needs Grammar Review
* Needs SEO Review
* Needs Tech Review
* Unlisted

- [ ] Should a reviewer get an activity item the first time they move a given post to a different status? Or should it be for activity each time they change a status for that post? The latter could be pretty noisy, so we might want to digest them, similar to #178.

> [username] Vetted a lesson plan on Learn WordPress
> [username] Reviewed SEO for a lesson plan on Learn WordPress
> [username] Requested more info for a lesson plan on Learn WordPress
vs simply
> [username] Reviewed a lesson plan on Learn WordPress

( Either way, they'd get at least one activity item for every post they review. I'm just asking if they should get 7 items for reviewing 7 things on the same post )

-------------------------------

- [ ] Should the activity include the title, even though the post isn't published yet? e.g.,

> [username] Reviewed a lesson plan on Learn WordPress
vs
> [username] Reviewed the lesson plan, _Anatomy Of A Theme_, on Learn WordPress

-------------------------------

- [ ] What about `declined` & `unlisted` statuses? Should those show up on a reviewers' profile? There could be similar privacy concerns to #177?

-------------------------------

- [ ] I don't see any kind of review process for Courses; is that correct?

**Comment by iandunn** [comment]
@courtneyr-dev , @angelasjin : do you have any thoughts on the questions above?
