### ISSUE TITLE
Consider launching end-to-end solution for a specific team

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/five-for-the-future#190]
Based on @iandunn's well documented work in #169, a few milestones were created:

1. [Track non-code contributions](https://github.com/WordPress/five-for-the-future/milestone/8)
2. [Notify inactive contributors](https://github.com/WordPress/five-for-the-future/milestone/9)
3. [Spam/dormant pledges - Future](https://github.com/WordPress/five-for-the-future/milestone/6)

Our current project structure assumes we will carry out work in the order listed above. 

**Question:** 
Can we work with a _medium-complexity_ team and complete their contribution tracking from end to end? If we were to take this approach, we could maybe gain better insights on how all the pieces fit together more quickly and lessen the risk of a lengthy iteration through milestone #8, seeing that milestone #8 involves numerous teams and environments -- which tends to lead to a slow feedback loop.

### What would we have to do?
Let's assume we try the documentation team first (only because we have feedback from the team in #178)

- Tracking:
  - Github: #178
    - Open/Close Tickets  
    - Comments
  - WordPress.org
    - Publish, Edit, Draft 
  - Slack
    -  #props
    -  meeting attendance #180
- Update Profile Data
  - #189 
 - Notify
   - #119
   - #27

I think we could aim at getting the "notify" emails going before any of the de-listing

**Comment by iandunn** [comment]
That's a great idea!

there'll be cases where someone contributes to team A and team B, but mostly team A. in those cases, we'd want to make sure we only notify them if we've got both teams covered. otherwise they could start getting notified b/c they haven't contributed to team B, even though they've contributed to team A.

maybe something like:

```
finished_teams = array( polyglots, documentation )

foreach user
   get all the teams the user reports as part of their 5ftF contribution
   if all teams of those teams are covered, then
       run notification code
   else
      skip them for now
```

**Comment by courtneyr-dev** [comment]
Raises hand to volunteer a team. We're small but have a lot of those things going on and would like to better track for 5ftF and unsponsored alike.

**Comment by tellyworth** [comment]
I think this is a great idea and the right way to go about it.

Once the team decision is clear and that team's activity is sufficiently well tracked, I'd suggest refining the milestone by punting issues like #185, #186, #188 to a later milestone, since they're about covering every team.

**Comment by angelasjin** [comment]
@courtneyr-dev can we ask the Training team trial this in coming months?

I'd like to also ask Polyglots to help, since we are recognizing more contribution activity there these days too.

**Comment by courtneyr-dev** [comment]
Revisiting this, and want to track the **Publish, Edit, Draft** areas. Do we have any means currently to surface those? Are there any API endpoints to start with?

**Comment by iandunn** [comment]
Since it's been hard to find time to complete the larger milestones, I wonder if we could do a lighter-weight version of this issue, where we:

- [ ] don't add any more tracking that what we already have
- [ ] enable the inactivity email notifications for all teams. "inactivity" would just be based on the last-login (#207)
- [ ] build the code to deactivate inactive contributors/companies, based on last-login (#214). this would essentially be the only new code being written, and the only significant time investment. that'd give us the essentials for all teams. 

then, in the future we could do something like:

- [ ] determine the teams that have enough tracking already
- [ ] determine which profile activities count as a 5ftf contribution (#119)
- [ ] start tracking the last 5ftf contribution for each profile (#189)
- [ ] for the teams above, start using the last contribution as the inactivity criteria, rather than last login (#210) 

then, over time we could add more teams to that list, once they have enough activity tracked (#207)
