### ISSUE TITLE
Tracking Contributions: Make Community Team

### ISSUE THREAD

**Issue by angelasjin** [WordPress/five-for-the-future#193]
In addition to issue #192, here are a few other suggestions for contributions that I wonder if we can automagically track for the Make Community team:

_( actionable ones have checkboxes, others are just bullet points )_

- [x] Publishing a new handbook page
- [x] Look into errors around new handbook pages 
- [x] Updating a handbook page (depends on #197 )
- Organizing or volunteering (in this case, volunteering would be one of the specified roles that people sign up for through the site) at a do_action event
- [x] Mentoring a WordCamp
- [ ] Vetting a Meetup or WordCamp application - maybe reuse `Event_Admin::get_props_for_event()` etc, but make sure get user ID not nicename
- [ ] Reviewing and approving a WC budget
- Running a Meetup or WordCamp orientation
- Creating a new Meetup or WordCamp site

There were a few other suggestions but I'm less sure how they could be tracked immediately. These included: 
- Responding to an incident report 
- Training deputies and mentors
- Sending swag
- Mentoring a meetup
- Holding the diverse speaker training workshop  
- Volunteering at a meetup
- Volunteering at a WordCamp

Deputies also voiced support for the following contributions, which is covered across other issues :
- Attended a team or working group meeting #180 
- Triaging Helpscout #177

**Comment by iandunn** [comment]
> Updating or publishing a new handbook page

I added publishing handbook pages in https://github.com/WordPress/wordpress.org/commit/3c872232db10fd5b1921ad33fb3a3ab7fcd4f574, but have seen some errors, so I need to circle back and do more testing.

For updating, we may want a digest mechanism (see #197), so that making 5 minor updates to the same page in an hour doesn't result in 5 different activity items.

**Comment by iandunn** [comment]
> Responding to an incident report

Does that happen in Help Scout? If so it'd probably be covered by #177.

> Holding the diverse speaker training workshop

Is that referring to the recorded version? I think that's covered in #179. Hosting the live version might be covered by #192 .

**Comment by angelasjin** [comment]
For Diverse Speaker Training, I think you're right that it will be covered by #179 and #192. 

For incident response, it does happen in HelpScout, but I'm not sure if that is the best way to recognize that work. Let's table responding to an incident report for now. Later this year, that team will have some more people around it, and we can revisit then around what we might be able to track and appropriately recognize.

**Comment by iandunn** [comment]
`Mentoring a WordCamp` is done now

![Screen Shot 2022-06-22 at 2 09 01 PM](https://user-images.githubusercontent.com/484068/175136485-5cb26b92-76b2-4dd7-bcb5-9acd0fbdd0be.png)

**Comment by iandunn** [comment]
> Vetting a Meetup or WordCamp application

* Should we still add an activity entry when the application is declined? Some privacy concerns were raised in #177 related to that kind of thing.
* Which status change(s) should trigger this? From `Needs Vetting` to any status (including `Needs More Info`)? Or only from  `Needs Vetting` to a final status, like `Needs Orientation` or `Declined`}. ? Or maybe from any status to any status?
* Should this only be applied once per camp, or multiple times? eg., if a reviewer moves to `needs more info` 3 times, then finally to `needs orientation`, should they get `4` entries on their profile, or `1`?
* Should the details be included in the message, like `Approved WordCamp Narnia application` and `Declined WordCamp Narnia application`, or just something generic like `Vetted WordCamp Narnia application` or even `Vetted a WordCamp application`.

**Comment by iandunn** [comment]
> `Reviewing and approving a WC budget`

I have similar questions to the above for this one:

* Should we still add an activity entry when the budget is declined? 
* Should the details be included in the message, like `Approved the budget for WordCamp Narnia` and `Declined the budget for WordCamp Narnia`, or just something generic like `Reviewed the budget for WordCamp Narnia` or `Reviewed a WordCamp budget`? 

Also, when an organizer clicks the `Save & Request Review` button on a preliminary budget, that sends an email to HelpScout and someone responds. AFAICT, though, those preliminary reviews don't have any status changes or actions on the website that we could track, so we don't know if/when it's been responded to, or how many times. Should we add some kind of extra step where the reviewer clicks a button whenever they review a preliminary budget, or do we only want to track the final approval?

**Comment by angelasjin** [comment]
I like what was suggested in issue #177 and wonder if we can do something similar for vetting applications. If someone has performed any status change up to a certain status, note that all together. 

For WordCamps, that would be changes to the following statuses:
- Needs Orientation/Interview
- More Info Requested
- Interview/Orientation Scheduled
- Declined
- Cancelled

For meetups, that would be changes to the following statuses:
- Awaiting Feedback
- Needs Orientation/Interview
- Scheduling
- Scheduled
- Changes requested
- Declined
- Canceled
- Dormant
- Removed from the chapter

Then, these status changes could be recorded monthly, like:

'Performed 75 actions for WordCamp vetting this month'
'Performed 63 actions for Meetup vetting this month'

For budget review, I think it will be ok to track final approval (other activity would be tracked through HS interactions). Would it be possible to do this by tracking who clicks "approve" in the specific WordCamp site, to create the approved budget? Otherwise, it could be done by tracking whoever moves the WC listing to `Needs contract to be signed`. I think the details would be:

'Approved the budget for WordCamp Narnia" 

I'm not inclined to track declining a budget, as that's commonly done during the budget review to make edits just before approving.

**Comment by iandunn** [comment]
That sounds good, thanks :)
